all:
	g++ -g -c Components/CpuJessePires/CpuJessePires.cpp
	g++ -g -c Components/DisplayJessePires/DisplayJessePires.cpp
	g++ -g -c Components/NumericKeyBoardJessePires/NumericKeyBoardJessePires.cpp
	g++ -g -c Components/OperationKeyBoardJessePires/OperationKeyBoardJessePires.cpp
	g++ -g -c CalculatorJessePires/CalculatorJessePires.cpp
	g++ -g -c main.cpp
	g++ -g CpuJessePires.o DisplayJessePires.o NumericKeyBoardJessePires.o OperationKeyBoardJessePires.o CalculatorJessePires.o main.o -o main
	