all:
	g++ -g -c modules/myCalculator.cpp
	g++ -g -c modules/CPU/myCPU.cpp
	g++ -g -c modules/Display/myDisplay.cpp
	g++ -g -c modules/NumericKeyBoard/myNumericKeyBoard.cpp
	g++ -g -c modules/OperationKeyBoard/myOperationKeyBoard.cpp
	g++ -g -c main.cpp
	g++ -o main *.o
	