USE pet_adopt;

#1 SELECIONE O NOME DOS VETERINARIOS E CACHORROS QUE REALIZARAM MAIS DE UM ATENDIMENTO
SELECT F.nome, C.nome AS nome_cachorro
FROM FUNCIONARIO F, CACHORRO C, ATENDIMENTO A
WHERE C.id = A.id_cachorro
AND F.cpf IN (
	SELECT V.cpf
    FROM VETERINARIO V
)
AND F.cpf = A.cpf_veterinario
GROUP BY F.nome, C.nome
HAVING COUNT(*) > 1; 


#2 SELECIONE O NOME DOS CACHORROS ADOTADOS PELOS CLIENTES ATENDIDOS PELA RECEPCIONISTA 'Amanda Tereza Aparício'
SELECT C.nome AS nome_cachorro
FROM CACHORRO C, FUNCIONARIO F, CLIENTE CL, RECEP_ATEND_CLIENTE RAC
WHERE CL.cpf = C.cpf_cliente
AND F.nome = 'Amanda Tereza Aparício'
AND F.cpf IN (
	SELECT R.cpf
    FROM RECEPCIONISTA R
)
AND F.cpf = RAC.cpf_recep
AND CL.cpf = RAC.cpf_cliente;

#3 SELECIONE A QUANTIDADE DE ATENDIMENTO QUE CADA RAÇA DE CACHORRO FEZ

SELECT COUNT(R2.nome) AS qtd_atendimento, R2.nome
FROM RACA R2, CACHORRO C2, ATENDIMENTO A2
WHERE R2.nome = C2.nome_raca
AND A2.id_cachorro = C2.id
GROUP BY R2.nome;


#4 SELECIONE O NOME DOS CACHORROS QUE NÃO REALIZARAM NENHUM TRATAMENTO
SELECT C.nome
FROM CACHORRO C
WHERE C.id NOT IN (
	SELECT C2.id
    FROM CACHORRO C2, ATENDIMENTO A2
    WHERE C2.id = A2.id_cachorro
);

# 5 SELECIONE O NOME E ENDEREÇO DOS CLIENTES QUE ADOTARAM CACHORROS DO PORTE 'G'
SELECT C.nome, E.tipo_logradouro, E.rua, E.numero, E.complemento
FROM CLIENTE C, ENDERECO E, CACHORRO CA
WHERE CA.cpf_cliente = C.cpf
AND CA.nome_raca IN (
	SELECT CA2.nome_raca
    FROM CACHORRO CA2, RACA R
    WHERE CA2.nome_raca = R.nome
    AND R.porte = 'G'
    
)
AND C.end_numero = E.numero
AND C.end_rua = E.rua;


# 6 - SELECIONE O ESTAGIARIO QUE MAIS FEZ COMPRAS DE RAÇÃO
SELECT F.nome
FROM FUNCIONARIO F, ESTAGIARIO E
WHERE F.cpf = E.cpf 
AND F.cpf = (
	SELECT E2.cpf
    FROM ESTAGIARIO E2, ESTAG_COMPRA_RACAO COMPRA_RACAO
    WHERE E2.cpf = COMPRA_RACAO.cpf_estag
    GROUP BY COMPRA_RACAO.cpf_estag
    ORDER BY SUM(COMPRA_RACAO.cpf_estag) DESC
    LIMIT 1
);

SELECT F.nome
FROM ESTAGIARIO E, ESTAG_COMPRA_RACAO COMPRA_RACAO, FUNCIONARIO F
WHERE E.cpf = F.cpf 
AND E.cpf = COMPRA_RACAO.cpf_estag
GROUP BY COMPRA_RACAO.cpf_estag
ORDER BY SUM(COMPRA_RACAO.cpf_estag) DESC
LIMIT 1;


# 7 - SELECIONE O NOME DO CACHORRO QUE MAIS FEZ TRATAMENTO
SELECT C.nome
FROM CACHORRO C, ATENDIMENTO A
WHERE C.id = A.id_cachorro
GROUP BY A.id_cachorro
ORDER BY SUM(A.id_cachorro) DESC
LIMIT 1;



# 8 - SELECIONE O NOME DOS CLIENTES QUE NÃO ADOTARAM NENHUM CACHORRO
SELECT C.nome
FROM CLIENTE C
WHERE C.cpf NOT IN (
	SELECT CA.cpf_cliente
    FROM CACHORRO CA
);


# 9 - SELECIONE O NOME DOS VETERINARIOS QUE NÃO REALIZARAM NENHUM ATENDIMENTO
SELECT F.nome
FROM VETERINARIO V, FUNCIONARIO F
WHERE V.cpf = F.cpf 
AND V.cpf NOT IN (
	SELECT A.cpf_veterinario
    FROM ATENDIMENTO A
);

# 10 - SELECIONE OS RECEPCIONISTAS QUE NÃO REALIZARAM ATENDERAM NENHUM CLIENTE
SELECT F.nome
FROM RECEPCIONISTA R, FUNCIONARIO F
WHERE R.cpf = F.cpf
AND R.cpf NOT IN (
	SELECT RAC.cpf_recep
    FROM RECEP_ATEND_CLIENTE RAC
);




