USE pet_adopt;

# SELECIONE O NOME DOS VETERINARIOS E CACHORROS QUE REALIZARAM MAIS DE UM ATENDIMENTO
SELECT F.nome, C.nome AS nome_cachorro
FROM FUNCIONARIO F, CACHORRO C, ATENDIMENTO A
WHERE C.id = A.id_cachorro
AND F.cpf IN (
	SELECT V.cpf
    FROM VETERINARIO V
)
AND F.cpf = A.cpf_veterinario
GROUP BY F.nome, C.nome
HAVING COUNT(*) > 1; 


# SELECIONE O NOME DOS CACHORROS ADOTADOS PELOS CLIENTES ATENDIDOS PELA RECEPCIONISTA 'Amanda Tereza Aparício'
SELECT C.nome AS nome_cachorro
FROM CACHORRO C, FUNCIONARIO F, CLIENTE CL, RECEP_ATEND_CLIENTE RAC
WHERE CL.cpf = C.cpf_cliente
AND F.nome = 'Amanda Tereza Aparício'
AND F.cpf IN (
	SELECT R.cpf
    FROM RECEPCIONISTA R
)
AND F.cpf = RAC.cpf_recep
AND CL.cpf = RAC.cpf_cliente;

# SELECIONE A QUANTIDADE DE ATENDIMENTO QUE CADA RAÇA DE CACHORRO FEZ

SELECT COUNT(R2.nome) AS qtd_atendimento, R2.nome
FROM RACA R2, CACHORRO C2, ATENDIMENTO A2
WHERE R2.nome = C2.nome_raca
AND A2.id_cachorro = C2.id
GROUP BY R2.nome;


# SELECIONE O NOME DOS CACHORROS QUE NÃO REALIZARAM NENHUM TRATAMENTO
SELECT C.nome
FROM CACHORRO C
WHERE C.id NOT IN (
	SELECT C2.id
    FROM CACHORRO C2, ATENDIMENTO A2
    WHERE C2.id = A2.id_cachorro
);

