all:
	g++ -g -c DAO/AlunoDAO.cpp
	g++ -g -c DAO/AvaliacaoFisica.cpp
	g++ -g -c DAO/FuncionarioDAO.cpp
	g++ -g -c DAO/InstrutorDAO.cpp

	g++ -g -c Entities/Aluno/Aluno.cpp
	g++ -g -c Entities/AvaliacaoFisica/AvaliacaoFisica.cpp
	g++ -g -c Entities/Funcionario/Funcionario.cpp
	g++ -g -c Entities/Instrutor/Instrutor.cpp
	g++ -g -c Entities/Pessoa/Pessoa.cpp
	g++ -g -c main.cpp

	g++ -o main *.o