all:

	g++ -g -c ArthurDaeSungHanCalc/calculator.cpp
	g++ -g -c ArthurDaeSungHanCalc/stack.cpp

	g++ -g -c MatheusKenjiNakao/calculatorNakao.cpp

	g++ -g -c CalculatorJessePires/Components/CpuJessePires/CpuJessePires.cpp
	g++ -g -c CalculatorJessePires/Components/DisplayJessePires/DisplayJessePires.cpp
	g++ -g -c CalculatorJessePires/Components/NumericKeyBoardJessePires/NumericKeyBoardJessePires.cpp
	g++ -g -c CalculatorJessePires/Components/OperationKeyBoardJessePires/OperationKeyBoardJessePires.cpp

	g++ -g -c JhonatanCalculator/JhonatanCalculator.cpp
	g++ -g -c JhonatanDisplay/JhonatanDisplay.cpp
	g++ -g -c JhonatanNumericKeyBoard/JhonatanNumericKeyBoard.cpp
	g++ -g -c JhonatanOperationKeyBoard/JhonatanOperationKeyBoard.cpp

	g++ -g -c InterfaceTest.cpp
	g++ -g -c main.cpp
	g++ -o main *.o
	