all:
	g++ -g -c CPU/myCPU.cpp
	g++ -g -c Display/myDisplay.cpp
	g++ -g -c NumericKeyBoard/myNumericKeyBoard.cpp
	g++ -g -c OperationKeyBoard/myOperationKeyBoard.cpp
	g++ -g -c Calculator/myCalculator.cpp
	g++ -g -c myInterfaceTest.cpp
	g++ -g -c main.cpp
	g++ -o main *.o
	