all:
	g++ -g -c JhonatanCPU/JhonatanCPU.cpp
	g++ -g -c JhonatanDisplay/JhonatanDisplay.cpp
	g++ -g -c JhonatanNumericKeyBoard/JhonatanNumericKeyBoard.cpp
	g++ -g -c JhonatanOperationKeyBoard/JhonatanOperationKeyBoard.cpp
	g++ -g -c JhonatanCalculator/JhonatanCalculator.cpp
	g++ -g -c InterfaceTest.cpp
	g++ -g -c main.cpp
	g++ -o main *.o
	