DROP DATABASE IF EXISTS escola2;
CREATE DATABASE escola2;
USE escola2;

DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS MEDICO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS QUARTO;
DROP TABLE IF EXISTS FORMACAO_MEDICO;
DROP TABLE IF EXISTS TRATAMENTO_PACIENTE;

CREATE TABLE ESPECIALIDADE (
	NOME VARCHAR(50),
    PRIMARY KEY(NOME)
);

CREATE TABLE MEDICO (
	CRM VARCHAR(10),
    NOME VARCHAR(100),
    SALARIO FLOAT(10, 2),
    NOME_ESPECIALIDADE VARCHAR(50),
    PRIMARY KEY (CRM),
    FOREIGN KEY (NOME_ESPECIALIDADE) REFERENCES ESPECIALIDADE(NOME)
);


CREATE TABLE PACIENTE(
	CPF CHAR(11),
    NOME VARCHAR(100),
    RG VARCHAR(11),
    CRM_MED_RESPONSAVEL VARCHAR(10),
    HORA_VISITA TIME,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CRM_MED_RESPONSAVEL) REFERENCES MEDICO(CRM)
);

CREATE TABLE QUARTO(
	NUMERO INTEGER,
    ANDAR INTEGER,
	CPF_PACIENTE CHAR(11) UNIQUE,
    PRIMARY KEY (NUMERO),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE FORMACAO_MEDICO(
	CRM_MEDICO VARCHAR(10),
    NOME_ESPECIALIDADE VARCHAR(50),
    PRIMARY KEY (CRM_MEDICO, NOME_ESPECIALIDADE),
    FOREIGN KEY (CRM_MEDICO) REFERENCES MEDICO(CRM),
    FOREIGN KEY (NOME_ESPECIALIDADE) REFERENCES ESPECIALIDADE(NOME)
);


CREATE TABLE TRATAMENTO_PACIENTE(
	CRM_MEDICO VARCHAR(10),
    CPF_PACIENTE CHAR(11),
	PRIMARY KEY (CRM_MEDICO, CPF_PACIENTE),
    FOREIGN KEY (CRM_MEDICO) REFERENCES MEDICO(CRM),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);
