DROP DATABASE IF EXISTS faculdade;
CREATE DATABASE faculdade;
USE faculdade;

CREATE TABLE PESSOA(
	CPF CHAR(11),
    PRIMARY KEY(CPF)
);

CREATE TABLE ALUNO (
	CPF_PESSOA CHAR(11),
    PRIMARY KEY(CPF_PESSOA),
    FOREIGN KEY(CPF_PESSOA) REFERENCES PESSOA(CPF)
);

CREATE TABLE PROFESSOR (
	CPF_PESSOA CHAR(11),
    PRIMARY KEY(CPF_PESSOA),
    FOREIGN KEY(CPF_PESSOA) REFERENCES PESSOA(CPF)
);

CREATE TABLE FUNCIONARIO (
	CPF_PESSOA CHAR(11),
    PRIMARY KEY(CPF_PESSOA),
    FOREIGN KEY(CPF_PESSOA) REFERENCES PESSOA(CPF)
);

CREATE TABLE FUNCIONARIO_AUXILIA_PROFESSOR(
	CPF_PROFESSOR CHAR(11),
    CPF_FUNCIONARIO CHAR(11),
    PRIMARY KEY(CPF_PROFESSOR, CPF_FUNCIONARIO),
    FOREIGN KEY(CPF_PROFESSOR) REFERENCES PROFESSOR(CPF_PESSOA),
    FOREIGN KEY(CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF_PESSOA)
);

CREATE TABLE INSCRICAO(
	CPF_PESSOA CHAR(11),
	ID INTEGER,
    INICIO DATE,
    FIM DATE,
    STATUS_INSCRICAO BOOL NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (CPF_PESSOA) REFERENCES PESSOA(CPF)
);


#AGREGAÇÃO
CREATE TABLE CURSO(
	NOME VARCHAR(100),
    PRIMARY KEY(NOME)
);

CREATE TABLE DISCIPLINA(
	NOME VARCHAR (100),
    PRIMARY KEY(NOME)
);

CREATE TABLE PRE_REQUISITO_DISCIPLINA(
	PRE_REQUISITADA VARCHAR (100),
    PRE_REQUISITO VARCHAR (100),
    SERIAL_SEQ VARCHAR(20),
    PRIMARY KEY(PRE_REQUISITADA, PRE_REQUISITO),
    FOREIGN KEY (PRE_REQUISITADA) REFERENCES DISCIPLINA(NOME),
	FOREIGN KEY (PRE_REQUISITO) REFERENCES DISCIPLINA(NOME)
);

CREATE TABLE CURSO_DISCIPLINA(
    NOME_CURSO VARCHAR(100),
    NOME_DISCIPLINA VARCHAR(100),
    PRIMARY KEY(NOME_CURSO, NOME_DISCIPLINA),
    FOREIGN KEY(NOME_CURSO) REFERENCES CURSO(NOME),
    FOREIGN KEY(NOME_DISCIPLINA) REFERENCES DISCIPLINA(NOME)
);

CREATE TABLE TURMA (
    CPF_PROFESSOR CHAR(11),
    SEMESTRE INTEGER,
    ANO INTEGER,
    NOME_CURSO_TURMA VARCHAR(100),
    NOME_DISCIPLINA_TURMA VARCHAR(100),
    
    PRIMARY KEY (SEMESTRE, NOME_CURSO_TURMA, NOME_DISCIPLINA_TURMA, ANO),
    
    FOREIGN KEY (CPF_PROFESSOR) REFERENCES PROFESSOR(CPF_PESSOA),
    FOREIGN KEY (NOME_CURSO_TURMA, NOME_DISCIPLINA_TURMA)
        REFERENCES CURSO_DISCIPLINA (NOME_CURSO, NOME_DISCIPLINA)
        ON DELETE CASCADE
);

CREATE TABLE INSCRICAO_TURMA (
	INSCRICAO_ID INTEGER,
	TURMA_SEMESTRE INTEGER,
    TURMA_ANO INTEGER,
	TURMA_NOME_CURSO VARCHAR(100),
    TURMA_NOME_DISCIPLINA VARCHAR(100),
    NOTA FLOAT(2, 2),
	
    PRIMARY KEY(INSCRICAO_ID, TURMA_SEMESTRE, TURMA_ANO, TURMA_NOME_CURSO, TURMA_NOME_DISCIPLINA),
    
    FOREIGN KEY (INSCRICAO_ID) REFERENCES INSCRICAO(ID),
	FOREIGN KEY (TURMA_SEMESTRE, TURMA_NOME_CURSO, TURMA_NOME_DISCIPLINA, TURMA_ANO) 
		    REFERENCES TURMA(SEMESTRE, NOME_CURSO_TURMA, NOME_DISCIPLINA_TURMA, ANO)
);
